services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: app
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  mq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build: .
    env_file: .env
    volumes:
      - ./:/app
      - storage:/app/storage
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mq

  worker:
    build: .
    env_file: .env
    command: celery -A app.tasks.worker worker --loglevel=INFO
    volumes:
      - ./:/app
      - storage:/app/storage
    depends_on:
      - db
      - mq

volumes:
  storage:
